// <auto-generated />
using System;
using Aurum.Api.Infrastructure.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Aurum.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260721013245_AddAuthHardening")]
    partial class AddAuthHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0-preview.1.25081.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "account_role", "account_role", new[] { "clearing" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bank_provider", "bank_provider", new[] { "BRI" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "bank_transaction_type", "bank_transaction_type", new[] { "credit", "debit" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "journal_kind", "journal_kind", new[] { "GJ", "AE", "CE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "period_status", "period_status", new[] { "open", "closing", "closed" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Aurum.Api.Features.Accounting.Accounts.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Ref")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("ref");

                    b.Property<int?>("Role")
                        .HasColumnType("account_role")
                        .HasColumnName("role");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("accounts_user_id_idx");

                    b.HasIndex("UserId", "Ref")
                        .IsUnique()
                        .HasDatabaseName("accounts_user_id_ref_uq");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Accounting.Periods.Entities.Period", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("My")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("my");

                    b.Property<decimal>("SeedBank")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("seed_bank");

                    b.Property<decimal>("SeedCash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("seed_cash");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("period_status")
                        .HasDefaultValue(0)
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("periods_user_id_idx");

                    b.HasIndex("UserId", "My")
                        .IsUnique()
                        .HasDatabaseName("periods_user_id_my_uq");

                    b.ToTable("periods", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Authentication.Entities.EmailVerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("email_verification_tokens_token_hash_uq");

                    b.HasIndex("UserId")
                        .HasDatabaseName("email_verification_tokens_user_id_idx");

                    b.ToTable("email_verification_tokens", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Authentication.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("password_reset_tokens_token_hash_uq");

                    b.HasIndex("UserId")
                        .HasDatabaseName("password_reset_tokens_user_id_idx");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Authentication.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReplacedByTokenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("refresh_tokens_token_hash_uq");

                    b.HasIndex("UserId")
                        .HasDatabaseName("refresh_tokens_user_id_idx");

                    b.ToTable("refresh_tokens", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.BankAccount.Entities.BankTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<string>("Category")
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTime>("TransactionDateUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("transaction_date");

                    b.Property<int>("Type")
                        .HasColumnType("bank_transaction_type")
                        .HasColumnName("type");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId")
                        .HasDatabaseName("bank_transactions_bank_account_id_idx");

                    b.HasIndex("UserId")
                        .HasDatabaseName("bank_transactions_user_id_idx");

                    b.ToTable("bank_transactions", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.BankAccount.Entities.LinkedBankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)")
                        .HasColumnName("account_number");

                    b.Property<decimal>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("balance");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("LastSyncedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_synced_at");

                    b.Property<int>("Provider")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bank_provider")
                        .HasDefaultValue(0)
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("bank_accounts_user_id_uq");

                    b.ToTable("bank_accounts", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Journals.Entities.JournalEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("account_ref");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("Credit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("credit");

                    b.Property<int>("Date")
                        .HasColumnType("integer")
                        .HasColumnName("date");

                    b.Property<decimal?>("Debit")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("debit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("description");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<bool>("IsClosingTemp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_closing_temp");

                    b.Property<int>("Kind")
                        .HasColumnType("journal_kind")
                        .HasColumnName("kind");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("PeriodId")
                        .HasDatabaseName("journal_entries_period_id_idx");

                    b.HasIndex("PeriodId", "Date")
                        .HasDatabaseName("journal_entries_period_id_date_idx");

                    b.HasIndex("UserId", "GroupId")
                        .HasDatabaseName("journal_entries_user_id_group_id_idx");

                    b.HasIndex("UserId", "PeriodId")
                        .HasDatabaseName("journal_entries_user_id_period_id_idx");

                    b.HasIndex("UserId", "PeriodId", "Kind")
                        .HasDatabaseName("journal_entries_user_id_period_id_kind_idx");

                    b.ToTable("journal_entries", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Ledger.Views.IncomeStatementRow", b =>
                {
                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_ref");

                    b.Property<decimal>("Net")
                        .HasColumnType("numeric")
                        .HasColumnName("net");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_income_statement", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Ledger.Views.TrialBalancePostRow", b =>
                {
                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_ref");

                    b.Property<decimal>("NetBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("net_balance");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_trial_balance_post", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Ledger.Views.TrialBalanceRow", b =>
                {
                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_name");

                    b.Property<string>("AccountRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_ref");

                    b.Property<decimal>("NetBalance")
                        .HasColumnType("numeric")
                        .HasColumnName("net_balance");

                    b.Property<Guid>("PeriodId")
                        .HasColumnType("uuid")
                        .HasColumnName("period_id");

                    b.Property<decimal>("TotalCredit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_credit");

                    b.Property<decimal>("TotalDebit")
                        .HasColumnType("numeric")
                        .HasColumnName("total_debit");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.ToTable((string)null);

                    b.ToView("vw_trial_balance", (string)null);
                });

            modelBuilder.Entity("Aurum.Api.Features.Users.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("EmailConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FailedLoginAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("FullName")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntilUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("User");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_uq");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
