ktor:
  deployment:
    port: 8080
  application:
    modules:
      - com.aurumfinance.SerializationKt.configureSerialization
      - com.aurumfinance.StatusPagesKt.configureStatusPages
      - com.aurumfinance.ResourcesKt.configureResources
      - com.aurumfinance.RoutingKt.configureRouting
